lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: Fernando Duarte, Chris Wyatt
  description: A test repo for the development of the initial FSP pipeline
  force: false
  is_nfcore: true
  name: fsptest
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - gpu
  version: 1.0.0dev
